export const GET_EMPRESAS_START = "GET_EMPRESAS_START";
export const GET_EMPRESAS_SUCCESS = "GET_EMPRESAS_SUCCESS";
export const GET_EMPRESAS_ERROR = "GET_EMPRESAS_ERROR";

export const POST_EMPRESA_START = "POST_EMPRESA_START";
export const POST_EMPRESA_SUCCESS = "POST_EMPRESA_SUCCESS";
export const POST_EMPRESA_ERROR = "POST_EMPRESA_ERROR";

export const DELETE_EMPRESA_START = "DELETE_EMPRESA_START";
export const DELETE_EMPRESA_SUCCESS = "DELETE_EMPRESA_SUCCESS";
export const DELETE_EMPRESA_ERROR = "DELETE_EMPRESA_ERROR";


export const UPDATE_EMPRESA_START = "UPDATE_EMPRESA_START";
export const UPDATE_EMPRESA_SUCCESS = "UPDATE_EMPRESA_SUCCESS";
export const UPDATE_EMPRESA_ERROR = "UPDATE_EMPRESA_ERROR";
